version: "3.9"
services:
  grafana:
    image: grafana/grafana
    depends_on:
    - "prometheus"
    ports:
    - 3000:3000
    volumes:
    - grafana-storage:/var/lib/grafana
    - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini
  prometheus:
    image: prom/prometheus
    depends_on:
    - "prometheus-push-gateway"
    ports:
    - 9090:9090
    volumes:
    - /etc/prometheus:/etc/prometheus
  prometheus-push-gateway:
    image: prom/pushgateway
    ports:
    - 9091:9091

volumes:
  grafana-storage:
